# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

install!'cocoapods',:deterministic_uuids=>false

target 'CSafariWebKit-Example' do
  use_frameworks!

  # Pods for CSafariWebKit-Example
  pod 'CSafariWebKit', :path => '../'

  target 'CSafariWebKit-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSafariWebKit-ExampleUITests' do
    # Pods for testing
  end

end
