# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSafariWebKit-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSafariWebKit-Example
  pod 'CSafariWebKit', :path => '../'

  target 'CSafariWebKit-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSafariWebKit-ExampleUITests' do
    # Pods for testing
  end

end
